version: "3.9"

services:
  db:
    image: postgres:17
    container_name: barrowspire_game_service_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: barrowspire_game_service_db
    ports:
      - "5143:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
