version: "3.9"

services:
  db:
    image: postgres:17
    container_name: barrowspire_items_service_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: barrowspire_items_service_db
    ports:
      - "5220:5432"
    volumes:
      - barrowspire_items_service_pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: barrowspire-redis
    ports:
      - "6492:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - barrowspire-network

volumes:
  barrowspire_items_service_pgdata:
  redis_data:
