// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/ledger/ledger.proto

package ledger

import (
	v1 "github.com/darkphotonKN/barrowspire-server/common/api/proto/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GetTransaction
// GET /api/ledger/transactions/:transaction_id
//
// The caller's account_id and role come from the JWT, never from the request —
// a member may only read a transaction they are a party to, and the handler
// masks the difference between "not yours" and "does not exist".
type GetTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *GetTransactionRequest) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TransactionId string                 `protobuf:"bytes,1,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,2,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Reason        string                 `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Currency      string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	Legs          []*Leg                 `protobuf:"bytes,5,rep,name=legs,proto3" json:"legs,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ledger_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *GetTransactionResponse) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *GetTransactionResponse) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *GetTransactionResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *GetTransactionResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *GetTransactionResponse) GetLegs() []*Leg {
	if x != nil {
		return x.Legs
	}
	return nil
}

func (x *GetTransactionResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// Leg is a leg as seen from inside its parent transaction: it carries no id,
// no transaction_id, and no timestamp, because all three are facts of the
// parent the reader already has. currency likewise sits on the transaction —
// one currency per transaction is structural, since sum-to-zero across mixed
// currencies is meaningless.
//
// Leg and Entry overlap and stay separate on purpose. They answer different
// questions: Leg is a component of a balanced whole, Entry is a standalone row
// in an account's history that must stand up without its parent alongside it.
// Collapsing them would force one message to carry fields that are redundant
// in one view and missing in the other.
type Leg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountId     string                 `protobuf:"bytes,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Direction     string                 `protobuf:"bytes,3,opt,name=direction,proto3" json:"direction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Leg) Reset() {
	*x = Leg{}
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Leg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Leg) ProtoMessage() {}

func (x *Leg) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Leg.ProtoReflect.Descriptor instead.
func (*Leg) Descriptor() ([]byte, []int) {
	return file_api_proto_ledger_ledger_proto_rawDescGZIP(), []int{2}
}

func (x *Leg) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Leg) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Leg) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

// ListEntries
// GET /api/ledger/entries?account_id={account_id?}&cursor={cursor}&limit={limit?}
type ListEntriesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Absent means "my own entries", resolved from the JWT.
	//
	// The optionality is load-bearing: presence is an admin-only request to read
	// someone else's history, so a member who sets this field is refused rather
	// than silently scoped back to themselves. proto3 `optional` is what makes
	// "unset" distinguishable from "set to the empty string" on the wire — with
	// a bare string the two collapse and that authorization signal is lost.
	AccountIdTarget *string `protobuf:"bytes,1,opt,name=account_id_target,json=accountIdTarget,proto3,oneof" json:"account_id_target,omitempty"`
	Cursor          string  `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit           int32   `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ListEntriesRequest) Reset() {
	*x = ListEntriesRequest{}
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesRequest) ProtoMessage() {}

func (x *ListEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesRequest.ProtoReflect.Descriptor instead.
func (*ListEntriesRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ledger_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *ListEntriesRequest) GetAccountIdTarget() string {
	if x != nil && x.AccountIdTarget != nil {
		return *x.AccountIdTarget
	}
	return ""
}

func (x *ListEntriesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListEntriesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	Pagination    *v1.PageInfo           `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListEntriesResponse) Reset() {
	*x = ListEntriesResponse{}
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListEntriesResponse) ProtoMessage() {}

func (x *ListEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListEntriesResponse.ProtoReflect.Descriptor instead.
func (*ListEntriesResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ledger_ledger_proto_rawDescGZIP(), []int{4}
}

func (x *ListEntriesResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *ListEntriesResponse) GetPagination() *v1.PageInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// Entry is one row of an account's history, denormalized so the feed pages
// without a join: reference_id, reason and currency are copied down from the
// parent transaction, and created_at is duplicated onto the row so the keyset
// cursor (created_at, id) orders entries directly.
type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TransactionId string                 `protobuf:"bytes,2,opt,name=transaction_id,json=transactionId,proto3" json:"transaction_id,omitempty"`
	ReferenceId   string                 `protobuf:"bytes,3,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	AccountId     string                 `protobuf:"bytes,5,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Direction     string                 `protobuf:"bytes,6,opt,name=direction,proto3" json:"direction,omitempty"`
	Currency      string                 `protobuf:"bytes,7,opt,name=currency,proto3" json:"currency,omitempty"`
	Amount        int64                  `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_api_proto_ledger_ledger_proto_rawDescGZIP(), []int{5}
}

func (x *Entry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entry) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *Entry) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *Entry) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *Entry) GetAccountId() string {
	if x != nil {
		return x.AccountId
	}
	return ""
}

func (x *Entry) GetDirection() string {
	if x != nil {
		return x.Direction
	}
	return ""
}

func (x *Entry) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Entry) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Entry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_proto_ledger_ledger_proto protoreflect.FileDescriptor

const file_api_proto_ledger_ledger_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/ledger/ledger.proto\x12\x06ledger\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$api/proto/shared/v1/pagination.proto\">\n" +
	"\x15GetTransactionRequest\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\"\xf2\x01\n" +
	"\x16GetTransactionResponse\x12%\n" +
	"\x0etransaction_id\x18\x01 \x01(\tR\rtransactionId\x12!\n" +
	"\freference_id\x18\x02 \x01(\tR\vreferenceId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12\x1f\n" +
	"\x04legs\x18\x05 \x03(\v2\v.ledger.LegR\x04legs\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"Z\n" +
	"\x03Leg\x12\x1d\n" +
	"\n" +
	"account_id\x18\x01 \x01(\tR\taccountId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12\x1c\n" +
	"\tdirection\x18\x03 \x01(\tR\tdirection\"\x89\x01\n" +
	"\x12ListEntriesRequest\x12/\n" +
	"\x11account_id_target\x18\x01 \x01(\tH\x00R\x0faccountIdTarget\x88\x01\x01\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limitB\x14\n" +
	"\x12_account_id_target\"s\n" +
	"\x13ListEntriesResponse\x12'\n" +
	"\aentries\x18\x01 \x03(\v2\r.ledger.EntryR\aentries\x123\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x13.shared.v1.PageInfoR\n" +
	"pagination\"\xa5\x02\n" +
	"\x05Entry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12%\n" +
	"\x0etransaction_id\x18\x02 \x01(\tR\rtransactionId\x12!\n" +
	"\freference_id\x18\x03 \x01(\tR\vreferenceId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x1d\n" +
	"\n" +
	"account_id\x18\x05 \x01(\tR\taccountId\x12\x1c\n" +
	"\tdirection\x18\x06 \x01(\tR\tdirection\x12\x1a\n" +
	"\bcurrency\x18\a \x01(\tR\bcurrency\x12\x16\n" +
	"\x06amount\x18\b \x01(\x03R\x06amount\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xac\x01\n" +
	"\rLedgerService\x12Q\n" +
	"\x0eGetTransaction\x12\x1d.ledger.GetTransactionRequest\x1a\x1e.ledger.GetTransactionResponse\"\x00\x12H\n" +
	"\vListEntries\x12\x1a.ledger.ListEntriesRequest\x1a\x1b.ledger.ListEntriesResponse\"\x00BDZBgithub.com/darkphotonKN/barrowspire-server/common/api/proto/ledgerb\x06proto3"

var (
	file_api_proto_ledger_ledger_proto_rawDescOnce sync.Once
	file_api_proto_ledger_ledger_proto_rawDescData []byte
)

func file_api_proto_ledger_ledger_proto_rawDescGZIP() []byte {
	file_api_proto_ledger_ledger_proto_rawDescOnce.Do(func() {
		file_api_proto_ledger_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ledger_ledger_proto_rawDesc), len(file_api_proto_ledger_ledger_proto_rawDesc)))
	})
	return file_api_proto_ledger_ledger_proto_rawDescData
}

var file_api_proto_ledger_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_ledger_ledger_proto_goTypes = []any{
	(*GetTransactionRequest)(nil),  // 0: ledger.GetTransactionRequest
	(*GetTransactionResponse)(nil), // 1: ledger.GetTransactionResponse
	(*Leg)(nil),                    // 2: ledger.Leg
	(*ListEntriesRequest)(nil),     // 3: ledger.ListEntriesRequest
	(*ListEntriesResponse)(nil),    // 4: ledger.ListEntriesResponse
	(*Entry)(nil),                  // 5: ledger.Entry
	(*timestamppb.Timestamp)(nil),  // 6: google.protobuf.Timestamp
	(*v1.PageInfo)(nil),            // 7: shared.v1.PageInfo
}
var file_api_proto_ledger_ledger_proto_depIdxs = []int32{
	2, // 0: ledger.GetTransactionResponse.legs:type_name -> ledger.Leg
	6, // 1: ledger.GetTransactionResponse.created_at:type_name -> google.protobuf.Timestamp
	5, // 2: ledger.ListEntriesResponse.entries:type_name -> ledger.Entry
	7, // 3: ledger.ListEntriesResponse.pagination:type_name -> shared.v1.PageInfo
	6, // 4: ledger.Entry.created_at:type_name -> google.protobuf.Timestamp
	0, // 5: ledger.LedgerService.GetTransaction:input_type -> ledger.GetTransactionRequest
	3, // 6: ledger.LedgerService.ListEntries:input_type -> ledger.ListEntriesRequest
	1, // 7: ledger.LedgerService.GetTransaction:output_type -> ledger.GetTransactionResponse
	4, // 8: ledger.LedgerService.ListEntries:output_type -> ledger.ListEntriesResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_api_proto_ledger_ledger_proto_init() }
func file_api_proto_ledger_ledger_proto_init() {
	if File_api_proto_ledger_ledger_proto != nil {
		return
	}
	file_api_proto_ledger_ledger_proto_msgTypes[3].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ledger_ledger_proto_rawDesc), len(file_api_proto_ledger_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ledger_ledger_proto_goTypes,
		DependencyIndexes: file_api_proto_ledger_ledger_proto_depIdxs,
		MessageInfos:      file_api_proto_ledger_ledger_proto_msgTypes,
	}.Build()
	File_api_proto_ledger_ledger_proto = out.File
	file_api_proto_ledger_ledger_proto_goTypes = nil
	file_api_proto_ledger_ledger_proto_depIdxs = nil
}
