// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/ledger/ledger.proto

package ledger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateLedger
// Empty by design: the member identity is derived from the authenticated
// context server-side, never supplied by the caller.
type CreateLedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLedgerRequest) Reset() {
	*x = CreateLedgerRequest{}
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerRequest) ProtoMessage() {}

func (x *CreateLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerRequest.ProtoReflect.Descriptor instead.
func (*CreateLedgerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

type CreateLedgerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLedgerResponse) Reset() {
	*x = CreateLedgerResponse{}
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLedgerResponse) ProtoMessage() {}

func (x *CreateLedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLedgerResponse.ProtoReflect.Descriptor instead.
func (*CreateLedgerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ledger_ledger_proto_rawDescGZIP(), []int{1}
}

func (x *CreateLedgerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateLedgerResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *CreateLedgerResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetLedger
// Empty by design, same rule as CreateLedgerRequest.
type GetLedgerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerRequest) Reset() {
	*x = GetLedgerRequest{}
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerRequest) ProtoMessage() {}

func (x *GetLedgerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerRequest.ProtoReflect.Descriptor instead.
func (*GetLedgerRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ledger_ledger_proto_rawDescGZIP(), []int{2}
}

type GetLedgerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLedgerResponse) Reset() {
	*x = GetLedgerResponse{}
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLedgerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLedgerResponse) ProtoMessage() {}

func (x *GetLedgerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ledger_ledger_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLedgerResponse.ProtoReflect.Descriptor instead.
func (*GetLedgerResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ledger_ledger_proto_rawDescGZIP(), []int{3}
}

func (x *GetLedgerResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetLedgerResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *GetLedgerResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_proto_ledger_ledger_proto protoreflect.FileDescriptor

const file_api_proto_ledger_ledger_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/ledger/ledger.proto\x12\x06ledger\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n" +
	"\x13CreateLedgerRequest\"~\n" +
	"\x14CreateLedgerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x12\n" +
	"\x10GetLedgerRequest\"{\n" +
	"\x11GetLedgerResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2\xa0\x01\n" +
	"\rLedgerService\x12K\n" +
	"\fCreateLedger\x12\x1b.ledger.CreateLedgerRequest\x1a\x1c.ledger.CreateLedgerResponse\"\x00\x12B\n" +
	"\tGetLedger\x12\x18.ledger.GetLedgerRequest\x1a\x19.ledger.GetLedgerResponse\"\x00BDZBgithub.com/darkphotonKN/barrowspire-server/common/api/proto/ledgerb\x06proto3"

var (
	file_api_proto_ledger_ledger_proto_rawDescOnce sync.Once
	file_api_proto_ledger_ledger_proto_rawDescData []byte
)

func file_api_proto_ledger_ledger_proto_rawDescGZIP() []byte {
	file_api_proto_ledger_ledger_proto_rawDescOnce.Do(func() {
		file_api_proto_ledger_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ledger_ledger_proto_rawDesc), len(file_api_proto_ledger_ledger_proto_rawDesc)))
	})
	return file_api_proto_ledger_ledger_proto_rawDescData
}

var file_api_proto_ledger_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_api_proto_ledger_ledger_proto_goTypes = []any{
	(*CreateLedgerRequest)(nil),   // 0: ledger.CreateLedgerRequest
	(*CreateLedgerResponse)(nil),  // 1: ledger.CreateLedgerResponse
	(*GetLedgerRequest)(nil),      // 2: ledger.GetLedgerRequest
	(*GetLedgerResponse)(nil),     // 3: ledger.GetLedgerResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_api_proto_ledger_ledger_proto_depIdxs = []int32{
	4, // 0: ledger.CreateLedgerResponse.created_at:type_name -> google.protobuf.Timestamp
	4, // 1: ledger.GetLedgerResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: ledger.LedgerService.CreateLedger:input_type -> ledger.CreateLedgerRequest
	2, // 3: ledger.LedgerService.GetLedger:input_type -> ledger.GetLedgerRequest
	1, // 4: ledger.LedgerService.CreateLedger:output_type -> ledger.CreateLedgerResponse
	3, // 5: ledger.LedgerService.GetLedger:output_type -> ledger.GetLedgerResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_ledger_ledger_proto_init() }
func file_api_proto_ledger_ledger_proto_init() {
	if File_api_proto_ledger_ledger_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ledger_ledger_proto_rawDesc), len(file_api_proto_ledger_ledger_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ledger_ledger_proto_goTypes,
		DependencyIndexes: file_api_proto_ledger_ledger_proto_depIdxs,
		MessageInfos:      file_api_proto_ledger_ledger_proto_msgTypes,
	}.Build()
	File_api_proto_ledger_ledger_proto = out.File
	file_api_proto_ledger_ledger_proto_goTypes = nil
	file_api_proto_ledger_ledger_proto_depIdxs = nil
}
