version: "3.9"

services:
  db:
    image: postgres:17
    container_name: barrowspire_example_service_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: barrowspire_example_service_db
    ports:
      - "5223:5432"
    volumes:
      - barrowspire_example_service_pgdata:/var/lib/postgresql/data

volumes:
  barrowspire_example_service_pgdata:
