// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/wallet/wallet.proto

package wallet

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateAccount
// Empty by design, same rule as GetAccountRequest: the member identity is
// derived from the authenticated context server-side, never supplied by the
// caller.
type CreateAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountRequest) Reset() {
	*x = CreateAccountRequest{}
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountRequest) ProtoMessage() {}

func (x *CreateAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_wallet_proto_rawDescGZIP(), []int{0}
}

// Newly birthed accounts hold no gold and carry no holds, so only the
// identity + birth facts are echoed back.
type CreateAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Gold          int64                  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"` // always 0 on creation, echoed for client convenience
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAccountResponse) Reset() {
	*x = CreateAccountResponse{}
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAccountResponse) ProtoMessage() {}

func (x *CreateAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_wallet_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAccountResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateAccountResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *CreateAccountResponse) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *CreateAccountResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// GetAccount
// Empty by design: the member identity is derived from the authenticated
// context server-side, never supplied by the caller.
type GetAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountRequest) Reset() {
	*x = GetAccountRequest{}
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountRequest) ProtoMessage() {}

func (x *GetAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountRequest.ProtoReflect.Descriptor instead.
func (*GetAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_wallet_proto_rawDescGZIP(), []int{2}
}

type GetAccountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Gold          int64                  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`                                        // total ledger balance
	HeldGold      int64                  `protobuf:"varint,4,opt,name=held_gold,json=heldGold,proto3" json:"held_gold,omitempty"`                // sum of RESERVED holds
	AvailableGold int64                  `protobuf:"varint,5,opt,name=available_gold,json=availableGold,proto3" json:"available_gold,omitempty"` // gold - held_gold, spendable now
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAccountResponse) Reset() {
	*x = GetAccountResponse{}
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountResponse) ProtoMessage() {}

func (x *GetAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountResponse.ProtoReflect.Descriptor instead.
func (*GetAccountResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_wallet_proto_rawDescGZIP(), []int{3}
}

func (x *GetAccountResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetAccountResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *GetAccountResponse) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *GetAccountResponse) GetHeldGold() int64 {
	if x != nil {
		return x.HeldGold
	}
	return 0
}

func (x *GetAccountResponse) GetAvailableGold() int64 {
	if x != nil {
		return x.AvailableGold
	}
	return 0
}

func (x *GetAccountResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// PlaceHold
// The account is resolved from the authenticated member in context server-side,
// so the caller only supplies what it owns: the amount and the bid it is for.
type PlaceHoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Gold          int64                  `protobuf:"varint,1,opt,name=gold,proto3" json:"gold,omitempty"`               // amount to reserve
	BidId         string                 `protobuf:"bytes,2,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"` // bid the hold is placed against
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceHoldRequest) Reset() {
	*x = PlaceHoldRequest{}
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceHoldRequest) ProtoMessage() {}

func (x *PlaceHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceHoldRequest.ProtoReflect.Descriptor instead.
func (*PlaceHoldRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_wallet_proto_rawDescGZIP(), []int{4}
}

func (x *PlaceHoldRequest) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *PlaceHoldRequest) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

// Empty by design: the hold either succeeds or the call fails with a status
// code. The caller addresses the hold by the bid_id it already owns.
type PlaceHoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceHoldResponse) Reset() {
	*x = PlaceHoldResponse{}
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceHoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceHoldResponse) ProtoMessage() {}

func (x *PlaceHoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceHoldResponse.ProtoReflect.Descriptor instead.
func (*PlaceHoldResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_wallet_proto_rawDescGZIP(), []int{5}
}

// CommitHold
// The hold is addressed by its bid, the natural idempotency key; the member is
// derived from the authenticated context server-side.
type CommitHoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidId         string                 `protobuf:"bytes,1,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"` // bid whose hold is being settled
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitHoldRequest) Reset() {
	*x = CommitHoldRequest{}
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitHoldRequest) ProtoMessage() {}

func (x *CommitHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitHoldRequest.ProtoReflect.Descriptor instead.
func (*CommitHoldRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_wallet_proto_rawDescGZIP(), []int{6}
}

func (x *CommitHoldRequest) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

// Empty by design, same rule as PlaceHoldResponse: success or a status code.
type CommitHoldResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommitHoldResponse) Reset() {
	*x = CommitHoldResponse{}
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommitHoldResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommitHoldResponse) ProtoMessage() {}

func (x *CommitHoldResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_wallet_wallet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommitHoldResponse.ProtoReflect.Descriptor instead.
func (*CommitHoldResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_wallet_wallet_proto_rawDescGZIP(), []int{7}
}

var File_api_proto_wallet_wallet_proto protoreflect.FileDescriptor

const file_api_proto_wallet_wallet_proto_rawDesc = "" +
	"\n" +
	"\x1dapi/proto/wallet/wallet.proto\x12\x06wallet\x1a\x1fgoogle/protobuf/timestamp.proto\"\x13\n" +
	"\x11GetAccountRequest\"\xd4\x01\n" +
	"\x12GetAccountResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x12\n" +
	"\x04gold\x18\x03 \x01(\x03R\x04gold\x12\x1b\n" +
	"\theld_gold\x18\x04 \x01(\x03R\bheldGold\x12%\n" +
	"\x0eavailable_gold\x18\x05 \x01(\x03R\ravailableGold\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2V\n" +
	"\rWalletService\x12E\n" +
	"\n" +
	"GetAccount\x12\x19.wallet.GetAccountRequest\x1a\x1a.wallet.GetAccountResponse\"\x00BDZBgithub.com/darkphotonKN/barrowspire-server/common/api/proto/walletb\x06proto3"

var (
	file_api_proto_wallet_wallet_proto_rawDescOnce sync.Once
	file_api_proto_wallet_wallet_proto_rawDescData []byte
)

func file_api_proto_wallet_wallet_proto_rawDescGZIP() []byte {
	file_api_proto_wallet_wallet_proto_rawDescOnce.Do(func() {
		file_api_proto_wallet_wallet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_wallet_wallet_proto_rawDesc), len(file_api_proto_wallet_wallet_proto_rawDesc)))
	})
	return file_api_proto_wallet_wallet_proto_rawDescData
}

var file_api_proto_wallet_wallet_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_api_proto_wallet_wallet_proto_goTypes = []any{
	(*CreateAccountRequest)(nil),  // 0: wallet.CreateAccountRequest
	(*CreateAccountResponse)(nil), // 1: wallet.CreateAccountResponse
	(*GetAccountRequest)(nil),     // 2: wallet.GetAccountRequest
	(*GetAccountResponse)(nil),    // 3: wallet.GetAccountResponse
	(*PlaceHoldRequest)(nil),      // 4: wallet.PlaceHoldRequest
	(*PlaceHoldResponse)(nil),     // 5: wallet.PlaceHoldResponse
	(*CommitHoldRequest)(nil),     // 6: wallet.CommitHoldRequest
	(*CommitHoldResponse)(nil),    // 7: wallet.CommitHoldResponse
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_api_proto_wallet_wallet_proto_depIdxs = []int32{
	8, // 0: wallet.CreateAccountResponse.created_at:type_name -> google.protobuf.Timestamp
	8, // 1: wallet.GetAccountResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 2: wallet.WalletService.CreateAccount:input_type -> wallet.CreateAccountRequest
	2, // 3: wallet.WalletService.GetAccount:input_type -> wallet.GetAccountRequest
	4, // 4: wallet.WalletService.PlaceHold:input_type -> wallet.PlaceHoldRequest
	6, // 5: wallet.WalletService.CommitHold:input_type -> wallet.CommitHoldRequest
	1, // 6: wallet.WalletService.CreateAccount:output_type -> wallet.CreateAccountResponse
	3, // 7: wallet.WalletService.GetAccount:output_type -> wallet.GetAccountResponse
	5, // 8: wallet.WalletService.PlaceHold:output_type -> wallet.PlaceHoldResponse
	7, // 9: wallet.WalletService.CommitHold:output_type -> wallet.CommitHoldResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_wallet_wallet_proto_init() }
func file_api_proto_wallet_wallet_proto_init() {
	if File_api_proto_wallet_wallet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_wallet_wallet_proto_rawDesc), len(file_api_proto_wallet_wallet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_wallet_wallet_proto_goTypes,
		DependencyIndexes: file_api_proto_wallet_wallet_proto_depIdxs,
		MessageInfos:      file_api_proto_wallet_wallet_proto_msgTypes,
	}.Build()
	File_api_proto_wallet_wallet_proto = out.File
	file_api_proto_wallet_wallet_proto_goTypes = nil
	file_api_proto_wallet_wallet_proto_depIdxs = nil
}
