syntax = "proto3";
package events;

import "google/protobuf/timestamp.proto";

option go_package = "github.com/darkphotonKN/barrowspire-server/common/api/proto/events";


message ItemCreatedEvent {
  string user_id = 1;
  string name = 2;
  string item_type = 3;
}

message ItemInstance {
  string id          = 1;
  string template_id = 2;
  string owner_member_id = 3;
  string source     = 4;
  string item_type = 5;              // 'weapon' | 'armor' | 'consumable'
  string name = 6;
  optional string rarity_id = 7;     // UUID as string

  // Weapon stats (null if not weapon)
  optional int32 attack_power = 8;
  optional double critical_rate = 9;
  optional string weapon_type = 10;

  // Armor stats (null if not armor)
  optional int32 defense_rating = 11;
  optional int32 magic_resistance = 12;
  optional string armor_slot = 13;   // 'head' | 'chest' | 'legs' | 'gloves'

  // Consumable stats (null if not consumable)
  optional int32 healing_amount = 14;
  optional int32 mana_amount = 15;
  optional int32 buff_duration = 16;

  optional int32 durability = 17;
  optional string description = 18;
  string status = 19; 
}


message ItemReservedEvent {
  string id = 1;
  string event_id = 2;
  string seller_id = 3;
  int64 start_price = 4; 
  google.protobuf.Timestamp ends_at = 5; 
  ItemInstance itemInstance = 6;
}