// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: api/proto/marketplace/marketplace.proto

package marketplace

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MarketplaceService_ListItem_FullMethodName       = "/marketplace.MarketplaceService/ListItem"
	MarketplaceService_ListMyListings_FullMethodName = "/marketplace.MarketplaceService/ListMyListings"
	MarketplaceService_BrowseListings_FullMethodName = "/marketplace.MarketplaceService/BrowseListings"
	MarketplaceService_GetListing_FullMethodName     = "/marketplace.MarketplaceService/GetListing"
	MarketplaceService_PlaceBid_FullMethodName       = "/marketplace.MarketplaceService/PlaceBid"
	MarketplaceService_WithdrawBid_FullMethodName    = "/marketplace.MarketplaceService/WithdrawBid"
	MarketplaceService_AcceptBid_FullMethodName      = "/marketplace.MarketplaceService/AcceptBid"
	MarketplaceService_Buyout_FullMethodName         = "/marketplace.MarketplaceService/Buyout"
)

// MarketplaceServiceClient is the client API for MarketplaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Marketplace service definition for listings and bids.
type MarketplaceServiceClient interface {
	// List one of the caller's items for sale at the given start price and end time.
	ListItem(ctx context.Context, in *ListItemRequest, opts ...grpc.CallOption) (*ListItemResponse, error)
	// The caller's own listings, newest first, paged by cursor.
	ListMyListings(ctx context.Context, in *ListMyListingsRequest, opts ...grpc.CallOption) (*ListMyListingsResponse, error)
	// Every seller's live auctions (ACTIVE, not yet ended), soonest-ending first,
	// paged by cursor. Public: needs no caller.
	BrowseListings(ctx context.Context, in *BrowseListingsRequest, opts ...grpc.CallOption) (*BrowseListingsResponse, error)
	// One listing in any status, with its price facts. Public: needs no caller.
	// An unknown id is NotFound.
	GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*GetListingResponse, error)
	// Place a bid on an active listing, taking the lead from the current winner.
	PlaceBid(ctx context.Context, in *PlaceBidRequest, opts ...grpc.CallOption) (*PlaceBidResponse, error)
	// Cancel a bid the caller placed.
	WithdrawBid(ctx context.Context, in *WithdrawBidRequest, opts ...grpc.CallOption) (*WithdrawBidResponse, error)
	// The seller ends their auction early at its current WINNING bid. Starts
	// settlement and returns; the sale completes asynchronously.
	AcceptBid(ctx context.Context, in *AcceptBidRequest, opts ...grpc.CallOption) (*AcceptBidResponse, error)
	// Buyout buys the listing outright at its buyout price and starts
	// settlement; the sale completes asynchronously (FS-NXP1W Req 4). The buyer
	// is the authenticated caller.
	Buyout(ctx context.Context, in *BuyoutRequest, opts ...grpc.CallOption) (*BuyoutResponse, error)
}

type marketplaceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMarketplaceServiceClient(cc grpc.ClientConnInterface) MarketplaceServiceClient {
	return &marketplaceServiceClient{cc}
}

func (c *marketplaceServiceClient) ListItem(ctx context.Context, in *ListItemRequest, opts ...grpc.CallOption) (*ListItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListItemResponse)
	err := c.cc.Invoke(ctx, MarketplaceService_ListItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceServiceClient) ListMyListings(ctx context.Context, in *ListMyListingsRequest, opts ...grpc.CallOption) (*ListMyListingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListMyListingsResponse)
	err := c.cc.Invoke(ctx, MarketplaceService_ListMyListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceServiceClient) BrowseListings(ctx context.Context, in *BrowseListingsRequest, opts ...grpc.CallOption) (*BrowseListingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BrowseListingsResponse)
	err := c.cc.Invoke(ctx, MarketplaceService_BrowseListings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceServiceClient) GetListing(ctx context.Context, in *GetListingRequest, opts ...grpc.CallOption) (*GetListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetListingResponse)
	err := c.cc.Invoke(ctx, MarketplaceService_GetListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceServiceClient) PlaceBid(ctx context.Context, in *PlaceBidRequest, opts ...grpc.CallOption) (*PlaceBidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlaceBidResponse)
	err := c.cc.Invoke(ctx, MarketplaceService_PlaceBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceServiceClient) WithdrawBid(ctx context.Context, in *WithdrawBidRequest, opts ...grpc.CallOption) (*WithdrawBidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WithdrawBidResponse)
	err := c.cc.Invoke(ctx, MarketplaceService_WithdrawBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceServiceClient) AcceptBid(ctx context.Context, in *AcceptBidRequest, opts ...grpc.CallOption) (*AcceptBidResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcceptBidResponse)
	err := c.cc.Invoke(ctx, MarketplaceService_AcceptBid_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *marketplaceServiceClient) Buyout(ctx context.Context, in *BuyoutRequest, opts ...grpc.CallOption) (*BuyoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BuyoutResponse)
	err := c.cc.Invoke(ctx, MarketplaceService_Buyout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MarketplaceServiceServer is the server API for MarketplaceService service.
// All implementations must embed UnimplementedMarketplaceServiceServer
// for forward compatibility.
//
// Marketplace service definition for listings and bids.
type MarketplaceServiceServer interface {
	// List one of the caller's items for sale at the given start price and end time.
	ListItem(context.Context, *ListItemRequest) (*ListItemResponse, error)
	// The caller's own listings, newest first, paged by cursor.
	ListMyListings(context.Context, *ListMyListingsRequest) (*ListMyListingsResponse, error)
	// Every seller's live auctions (ACTIVE, not yet ended), soonest-ending first,
	// paged by cursor. Public: needs no caller.
	BrowseListings(context.Context, *BrowseListingsRequest) (*BrowseListingsResponse, error)
	// One listing in any status, with its price facts. Public: needs no caller.
	// An unknown id is NotFound.
	GetListing(context.Context, *GetListingRequest) (*GetListingResponse, error)
	// Place a bid on an active listing, taking the lead from the current winner.
	PlaceBid(context.Context, *PlaceBidRequest) (*PlaceBidResponse, error)
	// Cancel a bid the caller placed.
	WithdrawBid(context.Context, *WithdrawBidRequest) (*WithdrawBidResponse, error)
	// The seller ends their auction early at its current WINNING bid. Starts
	// settlement and returns; the sale completes asynchronously.
	AcceptBid(context.Context, *AcceptBidRequest) (*AcceptBidResponse, error)
	// Buyout buys the listing outright at its buyout price and starts
	// settlement; the sale completes asynchronously (FS-NXP1W Req 4). The buyer
	// is the authenticated caller.
	Buyout(context.Context, *BuyoutRequest) (*BuyoutResponse, error)
	mustEmbedUnimplementedMarketplaceServiceServer()
}

// UnimplementedMarketplaceServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMarketplaceServiceServer struct{}

func (UnimplementedMarketplaceServiceServer) ListItem(context.Context, *ListItemRequest) (*ListItemResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListItem not implemented")
}
func (UnimplementedMarketplaceServiceServer) ListMyListings(context.Context, *ListMyListingsRequest) (*ListMyListingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListMyListings not implemented")
}
func (UnimplementedMarketplaceServiceServer) BrowseListings(context.Context, *BrowseListingsRequest) (*BrowseListingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BrowseListings not implemented")
}
func (UnimplementedMarketplaceServiceServer) GetListing(context.Context, *GetListingRequest) (*GetListingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListing not implemented")
}
func (UnimplementedMarketplaceServiceServer) PlaceBid(context.Context, *PlaceBidRequest) (*PlaceBidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PlaceBid not implemented")
}
func (UnimplementedMarketplaceServiceServer) WithdrawBid(context.Context, *WithdrawBidRequest) (*WithdrawBidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WithdrawBid not implemented")
}
func (UnimplementedMarketplaceServiceServer) AcceptBid(context.Context, *AcceptBidRequest) (*AcceptBidResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptBid not implemented")
}
func (UnimplementedMarketplaceServiceServer) Buyout(context.Context, *BuyoutRequest) (*BuyoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Buyout not implemented")
}
func (UnimplementedMarketplaceServiceServer) mustEmbedUnimplementedMarketplaceServiceServer() {}
func (UnimplementedMarketplaceServiceServer) testEmbeddedByValue()                            {}

// UnsafeMarketplaceServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MarketplaceServiceServer will
// result in compilation errors.
type UnsafeMarketplaceServiceServer interface {
	mustEmbedUnimplementedMarketplaceServiceServer()
}

func RegisterMarketplaceServiceServer(s grpc.ServiceRegistrar, srv MarketplaceServiceServer) {
	// If the following call pancis, it indicates UnimplementedMarketplaceServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MarketplaceService_ServiceDesc, srv)
}

func _MarketplaceService_ListItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServiceServer).ListItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketplaceService_ListItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServiceServer).ListItem(ctx, req.(*ListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceService_ListMyListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListMyListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServiceServer).ListMyListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketplaceService_ListMyListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServiceServer).ListMyListings(ctx, req.(*ListMyListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceService_BrowseListings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BrowseListingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServiceServer).BrowseListings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketplaceService_BrowseListings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServiceServer).BrowseListings(ctx, req.(*BrowseListingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceService_GetListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServiceServer).GetListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketplaceService_GetListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServiceServer).GetListing(ctx, req.(*GetListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceService_PlaceBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServiceServer).PlaceBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketplaceService_PlaceBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServiceServer).PlaceBid(ctx, req.(*PlaceBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceService_WithdrawBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WithdrawBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServiceServer).WithdrawBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketplaceService_WithdrawBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServiceServer).WithdrawBid(ctx, req.(*WithdrawBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceService_AcceptBid_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcceptBidRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServiceServer).AcceptBid(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketplaceService_AcceptBid_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServiceServer).AcceptBid(ctx, req.(*AcceptBidRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MarketplaceService_Buyout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BuyoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MarketplaceServiceServer).Buyout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MarketplaceService_Buyout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MarketplaceServiceServer).Buyout(ctx, req.(*BuyoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MarketplaceService_ServiceDesc is the grpc.ServiceDesc for MarketplaceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MarketplaceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "marketplace.MarketplaceService",
	HandlerType: (*MarketplaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListItem",
			Handler:    _MarketplaceService_ListItem_Handler,
		},
		{
			MethodName: "ListMyListings",
			Handler:    _MarketplaceService_ListMyListings_Handler,
		},
		{
			MethodName: "BrowseListings",
			Handler:    _MarketplaceService_BrowseListings_Handler,
		},
		{
			MethodName: "GetListing",
			Handler:    _MarketplaceService_GetListing_Handler,
		},
		{
			MethodName: "PlaceBid",
			Handler:    _MarketplaceService_PlaceBid_Handler,
		},
		{
			MethodName: "WithdrawBid",
			Handler:    _MarketplaceService_WithdrawBid_Handler,
		},
		{
			MethodName: "AcceptBid",
			Handler:    _MarketplaceService_AcceptBid_Handler,
		},
		{
			MethodName: "Buyout",
			Handler:    _MarketplaceService_Buyout_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/marketplace/marketplace.proto",
}
