// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/marketplace/marketplace.proto

package marketplace

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateListing
// Empty by design: the member identity is derived from the authenticated
// context server-side, never supplied by the caller.
type CreateListingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingRequest) Reset() {
	*x = CreateListingRequest{}
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingRequest) ProtoMessage() {}

func (x *CreateListingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingRequest.ProtoReflect.Descriptor instead.
func (*CreateListingRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_marketplace_marketplace_proto_rawDescGZIP(), []int{0}
}

type CreateListingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Gold          int64                  `protobuf:"varint,3,opt,name=gold,proto3" json:"gold,omitempty"`                                        // total ledger balance
	HeldGold      int64                  `protobuf:"varint,4,opt,name=held_gold,json=heldGold,proto3" json:"held_gold,omitempty"`                // sum of RESERVED holds
	AvailableGold int64                  `protobuf:"varint,5,opt,name=available_gold,json=availableGold,proto3" json:"available_gold,omitempty"` // gold - held_gold, spendable now
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateListingResponse) Reset() {
	*x = CreateListingResponse{}
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateListingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateListingResponse) ProtoMessage() {}

func (x *CreateListingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateListingResponse.ProtoReflect.Descriptor instead.
func (*CreateListingResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_marketplace_marketplace_proto_rawDescGZIP(), []int{1}
}

func (x *CreateListingResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreateListingResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *CreateListingResponse) GetGold() int64 {
	if x != nil {
		return x.Gold
	}
	return 0
}

func (x *CreateListingResponse) GetHeldGold() int64 {
	if x != nil {
		return x.HeldGold
	}
	return 0
}

func (x *CreateListingResponse) GetAvailableGold() int64 {
	if x != nil {
		return x.AvailableGold
	}
	return 0
}

func (x *CreateListingResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_api_proto_marketplace_marketplace_proto protoreflect.FileDescriptor

const file_api_proto_marketplace_marketplace_proto_rawDesc = "" +
	"\n" +
	"'api/proto/marketplace/marketplace.proto\x12\vmarketplace\x1a\x1fgoogle/protobuf/timestamp.proto\"\x16\n" +
	"\x14CreateListingRequest\"\xd7\x01\n" +
	"\x15CreateListingResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x12\n" +
	"\x04gold\x18\x03 \x01(\x03R\x04gold\x12\x1b\n" +
	"\theld_gold\x18\x04 \x01(\x03R\bheldGold\x12%\n" +
	"\x0eavailable_gold\x18\x05 \x01(\x03R\ravailableGold\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt2n\n" +
	"\x12MarketplaceService\x12X\n" +
	"\rCreateListing\x12!.marketplace.CreateListingRequest\x1a\".marketplace.CreateListingResponse\"\x00BIZGgithub.com/darkphotonKN/barrowspire-server/common/api/proto/marketplaceb\x06proto3"

var (
	file_api_proto_marketplace_marketplace_proto_rawDescOnce sync.Once
	file_api_proto_marketplace_marketplace_proto_rawDescData []byte
)

func file_api_proto_marketplace_marketplace_proto_rawDescGZIP() []byte {
	file_api_proto_marketplace_marketplace_proto_rawDescOnce.Do(func() {
		file_api_proto_marketplace_marketplace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_marketplace_marketplace_proto_rawDesc), len(file_api_proto_marketplace_marketplace_proto_rawDesc)))
	})
	return file_api_proto_marketplace_marketplace_proto_rawDescData
}

var file_api_proto_marketplace_marketplace_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_marketplace_marketplace_proto_goTypes = []any{
	(*CreateListingRequest)(nil),  // 0: marketplace.CreateListingRequest
	(*CreateListingResponse)(nil), // 1: marketplace.CreateListingResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_api_proto_marketplace_marketplace_proto_depIdxs = []int32{
	2, // 0: marketplace.CreateListingResponse.created_at:type_name -> google.protobuf.Timestamp
	0, // 1: marketplace.MarketplaceService.CreateListing:input_type -> marketplace.CreateListingRequest
	1, // 2: marketplace.MarketplaceService.CreateListing:output_type -> marketplace.CreateListingResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_marketplace_marketplace_proto_init() }
func file_api_proto_marketplace_marketplace_proto_init() {
	if File_api_proto_marketplace_marketplace_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_marketplace_marketplace_proto_rawDesc), len(file_api_proto_marketplace_marketplace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_marketplace_marketplace_proto_goTypes,
		DependencyIndexes: file_api_proto_marketplace_marketplace_proto_depIdxs,
		MessageInfos:      file_api_proto_marketplace_marketplace_proto_msgTypes,
	}.Build()
	File_api_proto_marketplace_marketplace_proto = out.File
	file_api_proto_marketplace_marketplace_proto_goTypes = nil
	file_api_proto_marketplace_marketplace_proto_depIdxs = nil
}
