// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.27.1
// source: api/proto/marketplace/marketplace.proto

package marketplace

import (
	v1 "github.com/darkphotonKN/barrowspire-server/common/api/proto/shared/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A listing as its seller sees it. The optimistic-locking version is internal
// and deliberately absent.
type Listing struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SellerId      string                 `protobuf:"bytes,2,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	BuyerId       *string                `protobuf:"bytes,3,opt,name=buyer_id,json=buyerId,proto3,oneof" json:"buyer_id,omitempty"` // present once sold
	ItemId        string                 `protobuf:"bytes,4,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	StartPrice    int64                  `protobuf:"varint,5,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	SoldPrice     *int64                 `protobuf:"varint,6,opt,name=sold_price,json=soldPrice,proto3,oneof" json:"sold_price,omitempty"` // present once sold
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Listing) Reset() {
	*x = Listing{}
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Listing) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Listing) ProtoMessage() {}

func (x *Listing) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Listing.ProtoReflect.Descriptor instead.
func (*Listing) Descriptor() ([]byte, []int) {
	return file_api_proto_marketplace_marketplace_proto_rawDescGZIP(), []int{0}
}

func (x *Listing) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Listing) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *Listing) GetBuyerId() string {
	if x != nil && x.BuyerId != nil {
		return *x.BuyerId
	}
	return ""
}

func (x *Listing) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *Listing) GetStartPrice() int64 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

func (x *Listing) GetSoldPrice() int64 {
	if x != nil && x.SoldPrice != nil {
		return *x.SoldPrice
	}
	return 0
}

func (x *Listing) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Listing) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *Listing) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Listing) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ListItem
// Empty by design: the member identity is derived from the authenticated
// context server-side, never supplied by the caller.
type ListItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ItemId        string                 `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	StartPrice    int64                  `protobuf:"varint,2,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemRequest) Reset() {
	*x = ListItemRequest{}
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemRequest) ProtoMessage() {}

func (x *ListItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemRequest.ProtoReflect.Descriptor instead.
func (*ListItemRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_marketplace_marketplace_proto_rawDescGZIP(), []int{1}
}

func (x *ListItemRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ListItemRequest) GetStartPrice() int64 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

func (x *ListItemRequest) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

type ListItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ItemId        string                 `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	StartPrice    int64                  `protobuf:"varint,3,opt,name=start_price,json=startPrice,proto3" json:"start_price,omitempty"`
	SellerId      string                 `protobuf:"bytes,4,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	EndsAt        *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=ends_at,json=endsAt,proto3" json:"ends_at,omitempty"`
	CreateAt      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=create_at,json=createAt,proto3" json:"create_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListItemResponse) Reset() {
	*x = ListItemResponse{}
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListItemResponse) ProtoMessage() {}

func (x *ListItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListItemResponse.ProtoReflect.Descriptor instead.
func (*ListItemResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_marketplace_marketplace_proto_rawDescGZIP(), []int{2}
}

func (x *ListItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ListItemResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *ListItemResponse) GetStartPrice() int64 {
	if x != nil {
		return x.StartPrice
	}
	return 0
}

func (x *ListItemResponse) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *ListItemResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListItemResponse) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *ListItemResponse) GetCreateAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateAt
	}
	return nil
}

func (x *ListItemResponse) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

// ListMyListings
// The seller is derived from the authenticated context server-side, never
// supplied by the caller, so there is no field for choosing another member.
type ListMyListingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"` // opaque; empty for the first page
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyListingsRequest) Reset() {
	*x = ListMyListingsRequest{}
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyListingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyListingsRequest) ProtoMessage() {}

func (x *ListMyListingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyListingsRequest.ProtoReflect.Descriptor instead.
func (*ListMyListingsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_marketplace_marketplace_proto_rawDescGZIP(), []int{3}
}

func (x *ListMyListingsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListMyListingsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListMyListingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Listings      []*Listing             `protobuf:"bytes,1,rep,name=listings,proto3" json:"listings,omitempty"`
	Pagination    *v1.PageInfo           `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"` // absent on the last page
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMyListingsResponse) Reset() {
	*x = ListMyListingsResponse{}
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMyListingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMyListingsResponse) ProtoMessage() {}

func (x *ListMyListingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMyListingsResponse.ProtoReflect.Descriptor instead.
func (*ListMyListingsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_marketplace_marketplace_proto_rawDescGZIP(), []int{4}
}

func (x *ListMyListingsResponse) GetListings() []*Listing {
	if x != nil {
		return x.Listings
	}
	return nil
}

func (x *ListMyListingsResponse) GetPagination() *v1.PageInfo {
	if x != nil {
		return x.Pagination
	}
	return nil
}

// PlaceBid
// The bidder is derived from the authenticated context server-side, never
// supplied by the caller — same rule as ListMyListingsRequest.
type PlaceBidRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ListingId string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	Amount    int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	// Idempotency key for safe retries. Optional; when empty the bid is never
	// deduplicated, so a retried request becomes a second bid.
	IdempotencyKey string `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PlaceBidRequest) Reset() {
	*x = PlaceBidRequest{}
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidRequest) ProtoMessage() {}

func (x *PlaceBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidRequest.ProtoReflect.Descriptor instead.
func (*PlaceBidRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_marketplace_marketplace_proto_rawDescGZIP(), []int{5}
}

func (x *PlaceBidRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *PlaceBidRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PlaceBidRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type PlaceBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidId         string                 `protobuf:"bytes,1,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                  // WINNING on success
	CurrentPrice  int64                  `protobuf:"varint,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"` // what the listing now stands at
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlaceBidResponse) Reset() {
	*x = PlaceBidResponse{}
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlaceBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaceBidResponse) ProtoMessage() {}

func (x *PlaceBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaceBidResponse.ProtoReflect.Descriptor instead.
func (*PlaceBidResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_marketplace_marketplace_proto_rawDescGZIP(), []int{6}
}

func (x *PlaceBidResponse) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

func (x *PlaceBidResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PlaceBidResponse) GetCurrentPrice() int64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

// WithdrawBid
// Cancels a bid the caller placed. Ownership is enforced server-side; a bid
// belonging to another member is rejected rather than silently ignored.
type WithdrawBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ListingId     string                 `protobuf:"bytes,1,opt,name=listing_id,json=listingId,proto3" json:"listing_id,omitempty"`
	BidId         string                 `protobuf:"bytes,2,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawBidRequest) Reset() {
	*x = WithdrawBidRequest{}
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawBidRequest) ProtoMessage() {}

func (x *WithdrawBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawBidRequest.ProtoReflect.Descriptor instead.
func (*WithdrawBidRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_marketplace_marketplace_proto_rawDescGZIP(), []int{7}
}

func (x *WithdrawBidRequest) GetListingId() string {
	if x != nil {
		return x.ListingId
	}
	return ""
}

func (x *WithdrawBidRequest) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

type WithdrawBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidId         string                 `protobuf:"bytes,1,opt,name=bid_id,json=bidId,proto3" json:"bid_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`                                  // CANCELLED on success
	CurrentPrice  int64                  `protobuf:"varint,3,opt,name=current_price,json=currentPrice,proto3" json:"current_price,omitempty"` // falls back to the reserve if the leader withdrew
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawBidResponse) Reset() {
	*x = WithdrawBidResponse{}
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawBidResponse) ProtoMessage() {}

func (x *WithdrawBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_marketplace_marketplace_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawBidResponse.ProtoReflect.Descriptor instead.
func (*WithdrawBidResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_marketplace_marketplace_proto_rawDescGZIP(), []int{8}
}

func (x *WithdrawBidResponse) GetBidId() string {
	if x != nil {
		return x.BidId
	}
	return ""
}

func (x *WithdrawBidResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WithdrawBidResponse) GetCurrentPrice() int64 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

var File_api_proto_marketplace_marketplace_proto protoreflect.FileDescriptor

const file_api_proto_marketplace_marketplace_proto_rawDesc = "" +
	"\n" +
	"'api/proto/marketplace/marketplace.proto\x12\vmarketplace\x1a\x1fgoogle/protobuf/timestamp.proto\x1a$api/proto/shared/v1/pagination.proto\"\x93\x03\n" +
	"\aListing\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tseller_id\x18\x02 \x01(\tR\bsellerId\x12\x1e\n" +
	"\bbuyer_id\x18\x03 \x01(\tH\x00R\abuyerId\x88\x01\x01\x12\x17\n" +
	"\aitem_id\x18\x04 \x01(\tR\x06itemId\x12\x1f\n" +
	"\vstart_price\x18\x05 \x01(\x03R\n" +
	"startPrice\x12\"\n" +
	"\n" +
	"sold_price\x18\x06 \x01(\x03H\x01R\tsoldPrice\x88\x01\x01\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x123\n" +
	"\aends_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAtB\v\n" +
	"\t_buyer_idB\r\n" +
	"\v_sold_price\"\x80\x01\n" +
	"\x0fListItemRequest\x12\x17\n" +
	"\aitem_id\x18\x01 \x01(\tR\x06itemId\x12\x1f\n" +
	"\vstart_price\x18\x02 \x01(\x03R\n" +
	"startPrice\x123\n" +
	"\aends_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\"\xba\x02\n" +
	"\x10ListItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\aitem_id\x18\x02 \x01(\tR\x06itemId\x12\x1f\n" +
	"\vstart_price\x18\x03 \x01(\x03R\n" +
	"startPrice\x12\x1b\n" +
	"\tseller_id\x18\x04 \x01(\tR\bsellerId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x123\n" +
	"\aends_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\x06endsAt\x127\n" +
	"\tcreate_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\bcreateAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"E\n" +
	"\x15ListMyListingsRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"\x7f\n" +
	"\x16ListMyListingsResponse\x120\n" +
	"\blistings\x18\x01 \x03(\v2\x14.marketplace.ListingR\blistings\x123\n" +
	"\n" +
	"pagination\x18\x02 \x01(\v2\x13.shared.v1.PageInfoR\n" +
	"pagination\"q\n" +
	"\x0fPlaceBidRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"f\n" +
	"\x10PlaceBidResponse\x12\x15\n" +
	"\x06bid_id\x18\x01 \x01(\tR\x05bidId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x03R\fcurrentPrice\"J\n" +
	"\x12WithdrawBidRequest\x12\x1d\n" +
	"\n" +
	"listing_id\x18\x01 \x01(\tR\tlistingId\x12\x15\n" +
	"\x06bid_id\x18\x02 \x01(\tR\x05bidId\"i\n" +
	"\x13WithdrawBidResponse\x12\x15\n" +
	"\x06bid_id\x18\x01 \x01(\tR\x05bidId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12#\n" +
	"\rcurrent_price\x18\x03 \x01(\x03R\fcurrentPrice2\xdb\x02\n" +
	"\x12MarketplaceService\x12I\n" +
	"\bListItem\x12\x1c.marketplace.ListItemRequest\x1a\x1d.marketplace.ListItemResponse\"\x00\x12[\n" +
	"\x0eListMyListings\x12\".marketplace.ListMyListingsRequest\x1a#.marketplace.ListMyListingsResponse\"\x00\x12I\n" +
	"\bPlaceBid\x12\x1c.marketplace.PlaceBidRequest\x1a\x1d.marketplace.PlaceBidResponse\"\x00\x12R\n" +
	"\vWithdrawBid\x12\x1f.marketplace.WithdrawBidRequest\x1a .marketplace.WithdrawBidResponse\"\x00BIZGgithub.com/darkphotonKN/barrowspire-server/common/api/proto/marketplaceb\x06proto3"

var (
	file_api_proto_marketplace_marketplace_proto_rawDescOnce sync.Once
	file_api_proto_marketplace_marketplace_proto_rawDescData []byte
)

func file_api_proto_marketplace_marketplace_proto_rawDescGZIP() []byte {
	file_api_proto_marketplace_marketplace_proto_rawDescOnce.Do(func() {
		file_api_proto_marketplace_marketplace_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_marketplace_marketplace_proto_rawDesc), len(file_api_proto_marketplace_marketplace_proto_rawDesc)))
	})
	return file_api_proto_marketplace_marketplace_proto_rawDescData
}

var file_api_proto_marketplace_marketplace_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_proto_marketplace_marketplace_proto_goTypes = []any{
	(*Listing)(nil),                // 0: marketplace.Listing
	(*ListItemRequest)(nil),        // 1: marketplace.ListItemRequest
	(*ListItemResponse)(nil),       // 2: marketplace.ListItemResponse
	(*ListMyListingsRequest)(nil),  // 3: marketplace.ListMyListingsRequest
	(*ListMyListingsResponse)(nil), // 4: marketplace.ListMyListingsResponse
	(*PlaceBidRequest)(nil),        // 5: marketplace.PlaceBidRequest
	(*PlaceBidResponse)(nil),       // 6: marketplace.PlaceBidResponse
	(*WithdrawBidRequest)(nil),     // 7: marketplace.WithdrawBidRequest
	(*WithdrawBidResponse)(nil),    // 8: marketplace.WithdrawBidResponse
	(*timestamppb.Timestamp)(nil),  // 9: google.protobuf.Timestamp
	(*v1.PageInfo)(nil),            // 10: shared.v1.PageInfo
}
var file_api_proto_marketplace_marketplace_proto_depIdxs = []int32{
	9,  // 0: marketplace.Listing.ends_at:type_name -> google.protobuf.Timestamp
	9,  // 1: marketplace.Listing.created_at:type_name -> google.protobuf.Timestamp
	9,  // 2: marketplace.Listing.updated_at:type_name -> google.protobuf.Timestamp
	9,  // 3: marketplace.ListItemRequest.ends_at:type_name -> google.protobuf.Timestamp
	9,  // 4: marketplace.ListItemResponse.ends_at:type_name -> google.protobuf.Timestamp
	9,  // 5: marketplace.ListItemResponse.create_at:type_name -> google.protobuf.Timestamp
	9,  // 6: marketplace.ListItemResponse.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 7: marketplace.ListMyListingsResponse.listings:type_name -> marketplace.Listing
	10, // 8: marketplace.ListMyListingsResponse.pagination:type_name -> shared.v1.PageInfo
	1,  // 9: marketplace.MarketplaceService.ListItem:input_type -> marketplace.ListItemRequest
	3,  // 10: marketplace.MarketplaceService.ListMyListings:input_type -> marketplace.ListMyListingsRequest
	5,  // 11: marketplace.MarketplaceService.PlaceBid:input_type -> marketplace.PlaceBidRequest
	7,  // 12: marketplace.MarketplaceService.WithdrawBid:input_type -> marketplace.WithdrawBidRequest
	2,  // 13: marketplace.MarketplaceService.ListItem:output_type -> marketplace.ListItemResponse
	4,  // 14: marketplace.MarketplaceService.ListMyListings:output_type -> marketplace.ListMyListingsResponse
	6,  // 15: marketplace.MarketplaceService.PlaceBid:output_type -> marketplace.PlaceBidResponse
	8,  // 16: marketplace.MarketplaceService.WithdrawBid:output_type -> marketplace.WithdrawBidResponse
	13, // [13:17] is the sub-list for method output_type
	9,  // [9:13] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_api_proto_marketplace_marketplace_proto_init() }
func file_api_proto_marketplace_marketplace_proto_init() {
	if File_api_proto_marketplace_marketplace_proto != nil {
		return
	}
	file_api_proto_marketplace_marketplace_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_marketplace_marketplace_proto_rawDesc), len(file_api_proto_marketplace_marketplace_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_marketplace_marketplace_proto_goTypes,
		DependencyIndexes: file_api_proto_marketplace_marketplace_proto_depIdxs,
		MessageInfos:      file_api_proto_marketplace_marketplace_proto_msgTypes,
	}.Build()
	File_api_proto_marketplace_marketplace_proto = out.File
	file_api_proto_marketplace_marketplace_proto_goTypes = nil
	file_api_proto_marketplace_marketplace_proto_depIdxs = nil
}
