CREATE TABLE IF NOT EXISTS accounts (
    id UUID PRIMARY KEY,
    member_id UUID NOT NULL UNIQUE,
    gold BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
