// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/character/character.proto

package items

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Character struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Character) Reset() {
	*x = Character{}
	mi := &file_api_proto_character_character_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Character) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Character) ProtoMessage() {}

func (x *Character) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_character_character_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Character.ProtoReflect.Descriptor instead.
func (*Character) Descriptor() ([]byte, []int) {
	return file_api_proto_character_character_proto_rawDescGZIP(), []int{0}
}

func (x *Character) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetCharacterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCharacterRequest) Reset() {
	*x = GetCharacterRequest{}
	mi := &file_api_proto_character_character_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCharacterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCharacterRequest) ProtoMessage() {}

func (x *GetCharacterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_character_character_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCharacterRequest.ProtoReflect.Descriptor instead.
func (*GetCharacterRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_character_character_proto_rawDescGZIP(), []int{1}
}

func (x *GetCharacterRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

var File_api_proto_character_character_proto protoreflect.FileDescriptor

const file_api_proto_character_character_proto_rawDesc = "" +
	"\n" +
	"#api/proto/character/character.proto\x12\x05items\x1a\x1bgoogle/protobuf/empty.proto\"\x1b\n" +
	"\tCharacter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"%\n" +
	"\x13GetCharacterRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id2N\n" +
	"\x10CharacterService\x12:\n" +
	"\x0eListCharacters\x12\x16.google.protobuf.Empty\x1a\x10.items.CharacterBCZAgithub.com/darkphotonKN/barrowspire-server/common/api/proto/itemsb\x06proto3"

var (
	file_api_proto_character_character_proto_rawDescOnce sync.Once
	file_api_proto_character_character_proto_rawDescData []byte
)

func file_api_proto_character_character_proto_rawDescGZIP() []byte {
	file_api_proto_character_character_proto_rawDescOnce.Do(func() {
		file_api_proto_character_character_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_character_character_proto_rawDesc), len(file_api_proto_character_character_proto_rawDesc)))
	})
	return file_api_proto_character_character_proto_rawDescData
}

var file_api_proto_character_character_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_api_proto_character_character_proto_goTypes = []any{
	(*Character)(nil),           // 0: items.Character
	(*GetCharacterRequest)(nil), // 1: items.GetCharacterRequest
	(*emptypb.Empty)(nil),       // 2: google.protobuf.Empty
}
var file_api_proto_character_character_proto_depIdxs = []int32{
	2, // 0: items.CharacterService.ListCharacters:input_type -> google.protobuf.Empty
	0, // 1: items.CharacterService.ListCharacters:output_type -> items.Character
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_character_character_proto_init() }
func file_api_proto_character_character_proto_init() {
	if File_api_proto_character_character_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_character_character_proto_rawDesc), len(file_api_proto_character_character_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_character_character_proto_goTypes,
		DependencyIndexes: file_api_proto_character_character_proto_depIdxs,
		MessageInfos:      file_api_proto_character_character_proto_msgTypes,
	}.Build()
	File_api_proto_character_character_proto = out.File
	file_api_proto_character_character_proto_goTypes = nil
	file_api_proto_character_character_proto_depIdxs = nil
}
