CREATE TABLE IF NOT EXISTS ledgers (
    id UUID PRIMARY KEY,
    member_id UUID NOT NULL UNIQUE,
    version INT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
